{% set name = "yaqd-control" %}
{% set version = "2021.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: 9d88a8bad1c18e521e00f3ec7f9c71a6a12de6e28876809a2493497b32d74e26

build:
  noarch: python
  number: 0
  entry_points:
    - yaqd=yaqd_control.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - appdirs
    - click
    - colorama
    - yaqc
    - prettytable !=1.0.0
    - python >=3.7
    - toml
    - pip
    - flit
  run:
    - appdirs
    - click
    - colorama
    - yaqc
    - prettytable !=1.0.0
    - python >=3.7
    - toml

test:
  imports:
    - yaqd_control
  commands:
    - yaqd --help

about:
  home: https://yaq.fyi
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Command line tools for inspecting and controlling yaq daemons.
  doc_url: https://yaq.fyi
  dev_url: https://gitlab.com/yaq/yaqd-control

extra:
  recipe-maintainers:
    - untzag
    - ksunden
